In [4]:
import numpy as np

In [12]:
my_list = [1, 2, 3, 4, 5, 6]

my_array = np.array(my_list)

print(my_array.dtype), print(my_array.shape)

int64
(6,)


(None, None)

In [19]:
np.zeros(5)
np.ones((5, 10)) #filas, columnas
np.random.randint(0, 10, (5, 5))

np.arange(0, 10, 2)
np.linspace(0, 10, 101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [23]:
my_array **3 #elevado al cuadrado

np.sqrt(my_array ** 2)

%time np.sqrt(my_array ** 2) #cuanto tiempo tarda en ejecutar la linea de codigo

CPU times: user 14 µs, sys: 5 µs, total: 19 µs
Wall time: 22.4 µs


array([1., 2., 3., 4., 5., 6.])

Numpy Slicing

In [27]:
my_array = np.arange(1, 17) #arange para crear la dimension
my_array


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [29]:
my_array = my_array.reshape(4, 4) #reshape para cambiar la dimension
my_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [30]:
my_array[0:2, 0:2]

array([[1, 2],
       [5, 6]])

In [31]:
my_array[:, 0:2] #para todas las filas solo los 2 primeros valores

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

Numpy Masking

In [33]:
my_array < 40 #para ver por ejemplo mis clientes menores de 40 años

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [36]:
mask = my_array < 8
mask

array([[ True,  True,  True,  True],
       [ True,  True,  True, False],
       [False, False, False, False],
       [False, False, False, False]])

In [37]:
my_array[mask]

array([1, 2, 3, 4, 5, 6, 7])

In [38]:
len(my_array) #como mi array es bidimensional, la longitud la hace sobre el primer eje
              #con .shape veo la dimension de mi array

4

The Alien Invasion!

In [39]:
import numpy as np


fleet_data = np.array([
    [120, 40, 25, 2.5, 10],
    [85, 60, 30, 5.0, 5],
    [100, 50, 35, 4.5, 7],
    [120, 40, 25, 2.5, 9],
    [150, 50, 30, 3.0, 10],
], dtype=np.float32)

In [77]:
#numero de naves espaciales (ejercicio 1)
total_spaceship = len(fleet_data)
total_spaceship



5

In [83]:
#ejercicio 2
lenght_colum = fleet_data[:, 0] #para todas las filas solo la primera columna
width_colum = fleet_data[:, 1] #para todas las filas solo la segunda columna
heigh_colum = fleet_data[:, 2] #para todas las filas solo la tercera columna

average_spaceship_volum = lenght_colum * width_colum * heigh_colum
average_spaceship_volum.mean()

158600.0

In [84]:
#ejercicio 3
speed_colum = fleet_data[:, 3]
np.max(speed_colum), np.min(speed_colum), np.mean(speed_colum)

(5.0, 2.5, 3.5)

In [93]:
#ejercicio 4
MAX_POWER = 10
weapon_power_column = fleet_data[:, 4]
mask = weapon_power_column == MAX_POWER

np.count_nonzero(mask)

2

In [95]:
#ejercicio 5
MAX_POWER = 10
weapon_power_column
mask = weapon_power_column == MAX_POWER

In [90]:
mask, speed_colum

(array([ True, False, False, False,  True]),
 array([2.5, 5. , 4.5, 2.5, 3. ], dtype=float32))

In [92]:
max_power_spaceships_spreeds = speed_colum[mask]

3 EN RAYA

In [96]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])