# **NUMPY**

In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3, 4, 5, 6]

my_array = np.array(my_list) #crear un array er numpy

print(my_array.dtype), print(my_array.shape) #tipo y forma

int64
(6,)


(None, None)

In [3]:
np.zeros(5) #crea un array de ceros con 5 elementos. El resultado será un array unidimensional que contiene cinco ceros.
np.ones((5, 10)) #crear un array bidimensional de 5x10 y todos los elementos son iguales a 1.
np.random.randint(0, 10, (5, 5)) #generar un array bidimensional de números enteros aleatorios entre 0 y 10 con dimensiones 5x5. 

np.arange(0, 10, 2) #array unidimensional con valores que comienzan en 0, aumentan en pasos de 2 y son menores que 10
np.linspace(0, 10, 101) #array unidimensional de 101 elementos igualmente espaciados que van desde 0 hasta 10 (ambos inclusive) 

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [4]:
my_array **2 #elevado al cuadrado

np.sqrt(my_array ** 2) #obtengo un nuevo array pero con todos positivos, ya que se eleva al cuadrado y luego se hace la raíz cuadrada.

%time np.sqrt(my_array ** 2) #cuanto tiempo tarda en ejecutar la linea de codigo

CPU times: user 15 µs, sys: 6 µs, total: 21 µs
Wall time: 24.3 µs


array([1., 2., 3., 4., 5., 6.])

## Array Slicing

In [5]:
my_array = np.arange(1, 17) #arange para crear un array unidimensional
my_array #una secuencia que comienza en 1 y termina en 16 (17 no está incluido)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [6]:
my_array = my_array.reshape(4, 4) #reshape para cambiar la dimension
my_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [7]:
my_array[0:2, 0:2]

array([[1, 2],
       [5, 6]])

In [8]:
my_array[:, 0:2] #para todas las filas solo los 2 primeros valores

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

## Array Masking

In [9]:
my_array < 40 #para ver por ejemplo mis clientes menores de 40 años

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [10]:
mask = my_array < 8
mask

array([[ True,  True,  True,  True],
       [ True,  True,  True, False],
       [False, False, False, False],
       [False, False, False, False]])

In [11]:
my_array[mask]

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
len(my_array) #como mi array es bidimensional, la longitud la hace sobre el primer eje
              #con .shape veo la dimension de mi array

4

## The Alien Invasion!

In [13]:
import numpy as np


fleet_data = np.array([
    [120, 40, 25, 2.5, 10],
    [85, 60, 30, 5.0, 5],
    [100, 50, 35, 4.5, 7],
    [120, 40, 25, 2.5, 9],
    [150, 50, 30, 3.0, 10],
], dtype=np.float32)

In [14]:
#numero de naves espaciales (ejercicio 1)
total_spaceship = len(fleet_data) #calcula la longitud de la primera fila
total_spaceship

5

In [15]:
#ejercicio 2
lenght_colum = fleet_data[:, 0] #para todas las filas solo la primera columna
width_colum = fleet_data[:, 1] #para todas las filas solo la segunda columna
heigh_colum = fleet_data[:, 2] #para todas las filas solo la tercera columna

average_spaceship_volum = lenght_colum * width_colum * heigh_colum
average_spaceship_volum.mean() #mean hace la media

158600.0

In [16]:
#ejercicio 3
speed_colum = fleet_data[:, 3]
np.max(speed_colum), np.min(speed_colum), np.mean(speed_colum)

(5.0, 2.5, 3.5)

In [17]:
#ejercicio 4
MAX_POWER = 10
weapon_power_column = fleet_data[:, 4]
mask = weapon_power_column == MAX_POWER #creo la mascara para definir que si es == 10 es True y sino False

np.count_nonzero(mask) #dado que la máscara tiene valores True y False, np.count_nonzero() cuenta cuántos elementos son True

2

In [18]:
#ejercicio 5
MAX_POWER = 10
weapon_power_column
mask = weapon_power_column == MAX_POWER

In [19]:
mask, speed_colum

(array([ True, False, False, False,  True]),
 array([2.5, 5. , 4.5, 2.5, 3. ], dtype=float32))

## TIC TAC TOE GAME

In [20]:
import numpy as np

class TicTacToe:
    def __init__(self) -> None:
        #creamos un tablero vacio de dimension 3x3
        #el jugador X va a empezar el juego
    
        self.board = np.zeros((3, 3), dtype=np.int8)
        self.current_player = 1  # 1 representa jugador X, -1 representa jugador O
    
    def display_board(self) -> None:
        #muestra el estado actual del tablero del juego

        print(self.board)

    def make_move(self, row: int, col: int) -> None:
        #crea un movimiento en el tablero en una columna y fila especifica

        #Parameters:
        #row (int): The row index.
        #col(int): The colum index

        pass
    def check_winner(self) -> int:
        pass
    def check_row(self, row: np.ndarray) -> int:
        pass
    def is_board_full(self) -> bool:
        return np.all(self.board !=0)


In [ ]:
#Ejemplo de Uso
tic_tac_toe_game = TicTacToe()

while True:
    tic_tac_toe_game.display_board

    row = int(input("Enter row (0, 1, or 2): "))
    col = int(input("Enter column (0, 1, or 2): "))

    #para hacer un movimiento:
    tic_tac_toe_game.make_move(row, col)

    #para verificar quien es el ganador:
    winner = tic_tac_toe_game.check_winner()
    if winner:
        tic_tac_toe_game.display_board()
        print(f"Player {winner} wins!")
        break

    #en el caso de que sea empate:
    if tic_tac_toe_game.is_board_full():
        tic_tac_toe_game.display_board()
        print("Its a tie!")
        break

    #para cambiar al siguiente jugador:
    tic_tac_toe_game.current_player *= -1 #transforma 1 a -1 y -1 a 1